/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health check */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Health check successful */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['HealthResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/builds': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List team builds */
    get: {
      parameters: {
        query?: {
          /** @description Optional filter by build identifier, template identifier, or template alias. */
          build_id_or_template?: components['parameters']['build_id_or_template']
          /** @description Comma-separated list of build statuses to include. */
          statuses?: components['parameters']['build_statuses']
          /** @description Maximum number of items to return per page. */
          limit?: components['parameters']['builds_limit']
          /** @description Cursor returned by the previous list response in `created_at|build_id` format. */
          cursor?: components['parameters']['builds_cursor']
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successfully returned paginated builds. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['BuildsListResponse']
          }
        }
        400: components['responses']['400']
        401: components['responses']['401']
        403: components['responses']['403']
        500: components['responses']['500']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/builds/statuses': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get build statuses */
    get: {
      parameters: {
        query: {
          /** @description Comma-separated list of build IDs to get statuses for. */
          build_ids: components['parameters']['build_ids']
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successfully returned build statuses */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['BuildsStatusesResponse']
          }
        }
        400: components['responses']['400']
        401: components['responses']['401']
        403: components['responses']['403']
        500: components['responses']['500']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/builds/{build_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get build details */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Identifier of the build. */
          build_id: components['parameters']['build_id']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successfully returned build details. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['BuildInfo']
          }
        }
        401: components['responses']['401']
        403: components['responses']['403']
        404: components['responses']['404']
        500: components['responses']['500']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sandboxes/{sandboxID}/record': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get sandbox record */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Identifier of the sandbox. */
          sandboxID: components['parameters']['sandboxID']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successfully returned sandbox details. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['SandboxRecord']
          }
        }
        401: components['responses']['401']
        403: components['responses']['403']
        404: components['responses']['404']
        500: components['responses']['500']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    Error: {
      /**
       * Format: int32
       * @description Error code.
       */
      code: number
      /** @description Error message. */
      message: string
    }
    /**
     * @description Build status mapped for dashboard clients.
     * @enum {string}
     */
    BuildStatus: 'building' | 'failed' | 'success'
    ListedBuild: {
      /**
       * Format: uuid
       * @description Identifier of the build.
       */
      id: string
      /** @description Template alias when present, otherwise template ID. */
      template: string
      /** @description Identifier of the template. */
      templateId: string
      status: components['schemas']['BuildStatus']
      /** @description Failure message when status is `failed`, otherwise `null`. */
      statusMessage: string | null
      /**
       * Format: date-time
       * @description Build creation timestamp in RFC3339 format.
       */
      createdAt: string
      /**
       * Format: date-time
       * @description Build completion timestamp in RFC3339 format, if finished.
       */
      finishedAt: string | null
    }
    BuildsListResponse: {
      data: components['schemas']['ListedBuild'][]
      /** @description Cursor to pass to the next list request, or `null` if there is no next page. */
      nextCursor: string | null
    }
    BuildStatusItem: {
      /**
       * Format: uuid
       * @description Identifier of the build.
       */
      id: string
      status: components['schemas']['BuildStatus']
      /**
       * Format: date-time
       * @description Build completion timestamp in RFC3339 format, if finished.
       */
      finishedAt: string | null
      /** @description Failure message when status is `failed`, otherwise `null`. */
      statusMessage: string | null
    }
    BuildsStatusesResponse: {
      /** @description List of build statuses */
      buildStatuses: components['schemas']['BuildStatusItem'][]
    }
    BuildInfo: {
      /** @description Template names related to this build, if available. */
      names?: string[] | null
      /**
       * Format: date-time
       * @description Build creation timestamp in RFC3339 format.
       */
      createdAt: string
      /**
       * Format: date-time
       * @description Build completion timestamp in RFC3339 format, if finished.
       */
      finishedAt: string | null
      status: components['schemas']['BuildStatus']
      /** @description Failure message when status is `failed`, otherwise `null`. */
      statusMessage: string | null
    }
    /**
     * Format: int64
     * @description CPU cores for the sandbox
     */
    CPUCount: number
    /**
     * Format: int64
     * @description Memory for the sandbox in MiB
     */
    MemoryMB: number
    /**
     * Format: int64
     * @description Disk size for the sandbox in MiB
     */
    DiskSizeMB: number
    SandboxRecord: {
      /** @description Identifier of the template from which is the sandbox created */
      templateID: string
      /** @description Alias of the template */
      alias?: string
      /** @description Identifier of the sandbox */
      sandboxID: string
      /**
       * Format: date-time
       * @description Time when the sandbox was started
       */
      startedAt: string
      /**
       * Format: date-time
       * @description Time when the sandbox was stopped
       */
      stoppedAt?: string | null
      /** @description Base domain where the sandbox traffic is accessible */
      domain?: string | null
      cpuCount: components['schemas']['CPUCount']
      memoryMB: components['schemas']['MemoryMB']
      diskSizeMB: components['schemas']['DiskSizeMB']
    }
    HealthResponse: {
      /** @description Human-readable health check result. */
      message: string
    }
  }
  responses: {
    /** @description Bad request */
    400: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Authentication error */
    401: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Forbidden */
    403: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Not found */
    404: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Server error */
    500: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
  }
  parameters: {
    /** @description Identifier of the build. */
    build_id: string
    /** @description Identifier of the sandbox. */
    sandboxID: string
    /** @description Maximum number of items to return per page. */
    builds_limit: number
    /** @description Cursor returned by the previous list response in `created_at|build_id` format. */
    builds_cursor: string
    /** @description Optional filter by build identifier, template identifier, or template alias. */
    build_id_or_template: string
    /** @description Comma-separated list of build statuses to include. */
    build_statuses: components['schemas']['BuildStatus'][]
    /** @description Comma-separated list of build IDs to get statuses for. */
    build_ids: string[]
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
